# Generated by Django 5.1.15 on 2026-08-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('category', models.CharField(choices=[('WEB_DEVELOPMENT', 'Web Development'), ('MOBILE_DEVELOPMENT', 'Mobile Development'), ('UI_UX', 'UI/UX Design'), ('GRAPHIC_DESIGN', 'Graphic Design'), ('COPYWRITING', 'Copywriting'), ('VIDEO_EDITING', 'Video Editing'), ('AI_ML', 'AI/ML'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.freelancerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
