# Generated by Django 5.1.15 on 2026-08-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('PROFILE_CREATED', 'Profile Created'), ('PROFILE_UPDATED', 'Profile Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_ACCEPTED', 'Deal Accepted'), ('DEAL_SIGNED', 'Deal Signed'), ('DEAL_ACTIVATED', 'Deal Activated'), ('DEAL_COMPLETED', 'Deal Completed'), ('DEAL_CANCELLED', 'Deal Cancelled'), ('DEAL_DISPUTED', 'Deal Disputed'), ('COMPLETION_CONFIRMED', 'Completion Confirmed')], db_index=True, max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
