# Generated by Django 5.1.15 on 2026-08-23 12:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_deals', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_deals', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='deals', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_name_at_agreement', models.CharField(blank=True, max_length=200)),
                ('client_name_at_agreement', models.CharField(blank=True, max_length=200)),
                ('freelancer_username_at_agreement', models.CharField(blank=True, max_length=150)),
                ('client_username_at_agreement', models.CharField(blank=True, max_length=150)),
                ('agreed_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_currency', models.CharField(default='USD', max_length=3)),
                ('agreed_deadline', models.DateTimeField(blank=True, null=True)),
                ('agreed_scope', models.TextField(blank=True)),
                ('agreed_deliverables', models.TextField(blank=True)),
                ('agreed_working_hours', models.CharField(blank=True, max_length=100)),
                ('agreed_tags_snapshot', models.JSONField(blank=True, default=list)),
                ('proof_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of immutable deal terms, computed once at snapshot time.', max_length=64)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='deals.deal')),
            ],
            options={
                'verbose_name_plural': 'Deal snapshots',
            },
        ),
        migrations.CreateModel(
            name='CompletionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on_time', models.BooleanField()),
                ('compensation_received', models.BooleanField(default=True)),
                ('compensation_fair', models.BooleanField(default=True)),
                ('work_satisfactory', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='deals.deal')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('deal', 'submitted_by')},
            },
        ),
    ]
