# Generated by Django 5.1.15 on 2026-08-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_is_open_to_proposals_dealmessage_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='deal_attachments/'),
        ),
        migrations.AlterField(
            model_name='dealmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('PROPOSED', 'Deal proposed'), ('ACCEPTED', 'Deal accepted'), ('SIGNED', 'Deal signed'), ('COMPLETED', 'Deal completed'), ('CANCELLED', 'Deal cancelled'), ('DISPUTED', 'Deal disputed'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('APPLIED', 'Freelancer applied'), ('MESSAGE', 'New message')], max_length=20),
        ),
        migrations.CreateModel(
            name='DealDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('REFUND_CLIENT', 'Refund the client'), ('PROCEED_AS_IS', 'Proceed with the work as-is'), ('CANCEL_DEAL', 'Cancel the deal')], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='deals.deal')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
