# Generated by Django 5.1.15 on 2026-08-23 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(choices=[('CLIENT', 'Client'), ('FREELANCER', 'Freelancer')], max_length=20)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked')], default='VALID', max_length=20)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='deals.deal')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'unique_together': {('deal', 'signer_role')},
            },
        ),
    ]
