# Generated by Django 5.1.15 on 2026-08-23 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEAL_COMPLETED', 'Deal Completed'), ('ON_TIME_COMPLETION', 'On-Time Completion'), ('FAIR_COMPENSATION', 'Fair Compensation'), ('BOTH_CONFIRMED', 'Both Parties Confirmed'), ('DEAL_CANCELLED', 'Deal Cancelled'), ('DISPUTE_RAISED', 'Dispute Raised'), ('DISPUTE_RESOLVED', 'Dispute Resolved')], db_index=True, max_length=30)),
                ('score_delta', models.IntegerField(default=0, help_text='Change in score: positive for good, negative for bad')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_records', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completed_deals', models.PositiveIntegerField(default=0)),
                ('on_time_completions', models.PositiveIntegerField(default=0)),
                ('fair_compensation_count', models.PositiveIntegerField(default=0)),
                ('both_confirmed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_deals', models.PositiveIntegerField(default=0)),
                ('disputes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
